/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GW2CS;

/**
 *
 * @author Alumno
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelUsuario = new javax.swing.JPanel();
        etiUsuario = new javax.swing.JLabel();
        PanelPestañas = new javax.swing.JTabbedPane();
        PanelPersonajes = new javax.swing.JScrollPane();
        TablaPersonajes = new javax.swing.JTable();
        PanelClanes = new javax.swing.JScrollPane();
        TablaClanes = new javax.swing.JTable();
        PanelInformacion = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        PanelUsuario1 = new javax.swing.JPanel();
        etiUsuario1 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        BarraMenu = new javax.swing.JMenuBar();
        UsuarioMenu = new javax.swing.JMenu();
        itemModificarDatos = new javax.swing.JMenuItem();
        SeparadorUsuario2 = new javax.swing.JPopupMenu.Separator();
        itemCerrarUsuario = new javax.swing.JMenuItem();
        EditarMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        AyudaMenu = new javax.swing.JMenu();
        itemAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guild Wars 2 Character Search");
        setMinimumSize(new java.awt.Dimension(800, 600));

        PanelUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelUsuario.setAlignmentX(0.0F);
        PanelUsuario.setAlignmentY(0.0F);
        PanelUsuario.setPreferredSize(new java.awt.Dimension(221, 36));

        etiUsuario.setBackground(new java.awt.Color(200, 200, 200));
        etiUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        etiUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiUsuario.setText("Usuario");
        etiUsuario.setAlignmentY(0.0F);
        etiUsuario.setMaximumSize(new java.awt.Dimension(41, 20));
        etiUsuario.setMinimumSize(new java.awt.Dimension(41, 20));
        etiUsuario.setOpaque(true);
        etiUsuario.setPreferredSize(new java.awt.Dimension(41, 20));

        javax.swing.GroupLayout PanelUsuarioLayout = new javax.swing.GroupLayout(PanelUsuario);
        PanelUsuario.setLayout(PanelUsuarioLayout);
        PanelUsuarioLayout.setHorizontalGroup(
            PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUsuarioLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(etiUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        PanelUsuarioLayout.setVerticalGroup(
            PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUsuarioLayout.createSequentialGroup()
                .addComponent(etiUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 259, Short.MAX_VALUE))
        );

        TablaPersonajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        PanelPersonajes.setViewportView(TablaPersonajes);

        PanelPestañas.addTab("Personajes", PanelPersonajes);

        TablaClanes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        PanelClanes.setViewportView(TablaClanes);

        PanelPestañas.addTab("Clan", PanelClanes);

        PanelInformacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout PanelInformacionLayout = new javax.swing.GroupLayout(PanelInformacion);
        PanelInformacion.setLayout(PanelInformacionLayout);
        PanelInformacionLayout.setHorizontalGroup(
            PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );
        PanelInformacionLayout.setVerticalGroup(
            PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );

        PanelUsuario1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelUsuario1.setAlignmentX(0.0F);
        PanelUsuario1.setAlignmentY(0.0F);
        PanelUsuario1.setPreferredSize(new java.awt.Dimension(221, 36));

        etiUsuario1.setBackground(new java.awt.Color(200, 200, 200));
        etiUsuario1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        etiUsuario1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiUsuario1.setText("Búsqueda");
        etiUsuario1.setAlignmentY(0.0F);
        etiUsuario1.setMaximumSize(new java.awt.Dimension(41, 20));
        etiUsuario1.setMinimumSize(new java.awt.Dimension(41, 20));
        etiUsuario1.setOpaque(true);
        etiUsuario1.setPreferredSize(new java.awt.Dimension(41, 20));

        jRadioButton1.setText("Personaje");

        jRadioButton2.setText("Clan");

        jRadioButton3.setText("Cuenta");

        javax.swing.GroupLayout PanelUsuario1Layout = new javax.swing.GroupLayout(PanelUsuario1);
        PanelUsuario1.setLayout(PanelUsuario1Layout);
        PanelUsuario1Layout.setHorizontalGroup(
            PanelUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(etiUsuario1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelUsuario1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUsuario1Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(jRadioButton2))
                    .addComponent(txtBusqueda))
                .addContainerGap())
        );
        PanelUsuario1Layout.setVerticalGroup(
            PanelUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUsuario1Layout.createSequentialGroup()
                .addComponent(etiUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addGap(0, 198, Short.MAX_VALUE))
        );

        UsuarioMenu.setText("Usuario");

        itemModificarDatos.setText("Modificar datos...");
        UsuarioMenu.add(itemModificarDatos);
        UsuarioMenu.add(SeparadorUsuario2);

        itemCerrarUsuario.setText("Cerrar usuario");
        UsuarioMenu.add(itemCerrarUsuario);

        BarraMenu.add(UsuarioMenu);

        EditarMenu.setText("Editar");

        jMenuItem1.setText("Registrar Personaje...");
        EditarMenu.add(jMenuItem1);

        jMenuItem3.setText("Eliminar Personaje...");
        EditarMenu.add(jMenuItem3);
        EditarMenu.add(jSeparator1);

        jMenuItem4.setText("Registrar Clan...");
        EditarMenu.add(jMenuItem4);

        jMenuItem5.setText("Modificar Clan...");
        EditarMenu.add(jMenuItem5);

        jMenuItem6.setText("Eliminar Clan...");
        EditarMenu.add(jMenuItem6);

        BarraMenu.add(EditarMenu);

        AyudaMenu.setText("Ayuda");

        itemAcerca.setText("Acerca de...");
        AyudaMenu.add(itemAcerca);

        BarraMenu.add(AyudaMenu);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelPestañas, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PanelPestañas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AyudaMenu;
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JMenu EditarMenu;
    private javax.swing.JScrollPane PanelClanes;
    private javax.swing.JPanel PanelInformacion;
    private javax.swing.JScrollPane PanelPersonajes;
    private javax.swing.JTabbedPane PanelPestañas;
    private javax.swing.JPanel PanelUsuario;
    private javax.swing.JPanel PanelUsuario1;
    private javax.swing.JPopupMenu.Separator SeparadorUsuario2;
    private javax.swing.JTable TablaClanes;
    private javax.swing.JTable TablaPersonajes;
    private javax.swing.JMenu UsuarioMenu;
    private javax.swing.JLabel etiUsuario;
    private javax.swing.JLabel etiUsuario1;
    private javax.swing.JMenuItem itemAcerca;
    private javax.swing.JMenuItem itemCerrarUsuario;
    private javax.swing.JMenuItem itemModificarDatos;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
