/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Ever
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Registro = new javax.swing.JDialog();
        etiCuenta = new javax.swing.JLabel();
        etiEmail = new javax.swing.JLabel();
        etiContrasena = new javax.swing.JLabel();
        etiRepeContrasena = new javax.swing.JLabel();
        etiServidor = new javax.swing.JLabel();
        etiIdiomas = new javax.swing.JLabel();
        etiNivelFrac = new javax.swing.JLabel();
        txtCuenta = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JPasswordField();
        txtRepeContrasena = new javax.swing.JPasswordField();
        txtNivelFrac = new javax.swing.JTextField();
        combServidor = new javax.swing.JComboBox();
        panelIdiomas = new javax.swing.JPanel();
        chkIngles = new javax.swing.JCheckBox();
        chkEspanol = new javax.swing.JCheckBox();
        chkAleman = new javax.swing.JCheckBox();
        chkFrances = new javax.swing.JCheckBox();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        fondoRegistro = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        etiLoginCuenta = new javax.swing.JLabel();
        etiLoginContrasena = new javax.swing.JLabel();
        txtLoginCuenta = new javax.swing.JTextField();
        txtLoginContrasena = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fondoLogin = new javax.swing.JLabel();

        Registro.setTitle("Registro");
        Registro.setMaximumSize(new java.awt.Dimension(370, 400));
        Registro.setMinimumSize(new java.awt.Dimension(370, 400));
        Registro.setPreferredSize(new java.awt.Dimension(370, 400));
        Registro.setResizable(false);
        Registro.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiCuenta.setForeground(new java.awt.Color(209, 194, 170));
        etiCuenta.setText("Nombre cuenta (GW2)");
        Registro.getContentPane().add(etiCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 27, -1, -1));

        etiEmail.setForeground(new java.awt.Color(209, 194, 170));
        etiEmail.setText("Email");
        Registro.getContentPane().add(etiEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 65, 107, -1));

        etiContrasena.setForeground(new java.awt.Color(209, 194, 170));
        etiContrasena.setText("Contraseña");
        Registro.getContentPane().add(etiContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 103, 107, -1));

        etiRepeContrasena.setForeground(new java.awt.Color(209, 194, 170));
        etiRepeContrasena.setText("Repetir contraseña");
        Registro.getContentPane().add(etiRepeContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 144, 107, -1));

        etiServidor.setForeground(new java.awt.Color(209, 194, 170));
        etiServidor.setText("Servidor");
        Registro.getContentPane().add(etiServidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 217, 104, -1));

        etiIdiomas.setForeground(new java.awt.Color(209, 194, 170));
        etiIdiomas.setText("Idiomas");
        Registro.getContentPane().add(etiIdiomas, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 252, 104, -1));

        etiNivelFrac.setForeground(new java.awt.Color(209, 194, 170));
        etiNivelFrac.setText("Nivel de Fractales");
        Registro.getContentPane().add(etiNivelFrac, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 179, -1, -1));
        Registro.getContentPane().add(txtCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 24, 181, -1));
        Registro.getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 62, 181, -1));
        Registro.getContentPane().add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 100, 181, -1));
        Registro.getContentPane().add(txtRepeContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 138, 181, -1));
        Registro.getContentPane().add(txtNivelFrac, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 176, 181, -1));

        combServidor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combServidor.setOpaque(false);
        Registro.getContentPane().add(combServidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 214, 178, -1));

        panelIdiomas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(209, 194, 170), 1, true));
        panelIdiomas.setOpaque(false);

        chkIngles.setForeground(new java.awt.Color(209, 194, 170));
        chkIngles.setText("Inglés");
        chkIngles.setOpaque(false);

        chkEspanol.setForeground(new java.awt.Color(209, 194, 170));
        chkEspanol.setText("Español");
        chkEspanol.setOpaque(false);

        chkAleman.setForeground(new java.awt.Color(209, 194, 170));
        chkAleman.setText("Aleman");
        chkAleman.setOpaque(false);

        chkFrances.setForeground(new java.awt.Color(209, 194, 170));
        chkFrances.setText("Francés");
        chkFrances.setOpaque(false);

        javax.swing.GroupLayout panelIdiomasLayout = new javax.swing.GroupLayout(panelIdiomas);
        panelIdiomas.setLayout(panelIdiomasLayout);
        panelIdiomasLayout.setHorizontalGroup(
            panelIdiomasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIdiomasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIdiomasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkIngles)
                    .addComponent(chkAleman))
                .addGap(41, 41, 41)
                .addGroup(panelIdiomasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkEspanol)
                    .addComponent(chkFrances))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelIdiomasLayout.setVerticalGroup(
            panelIdiomasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIdiomasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIdiomasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkIngles)
                    .addComponent(chkEspanol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelIdiomasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkAleman)
                    .addComponent(chkFrances))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Registro.getContentPane().add(panelIdiomas, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 252, -1, -1));

        btnAceptar.setText("Aceptar");
        btnAceptar.setOpaque(false);
        Registro.getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.setOpaque(false);
        Registro.getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        fondoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/fondo2.jpg"))); // NOI18N
        Registro.getContentPane().add(fondoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 390));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiLoginCuenta.setForeground(new java.awt.Color(209, 194, 170));
        etiLoginCuenta.setText("Usuario");
        jPanel1.add(etiLoginCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 56, -1));

        etiLoginContrasena.setForeground(new java.awt.Color(209, 194, 170));
        etiLoginContrasena.setText("Contraseña");
        jPanel1.add(etiLoginContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        txtLoginCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(txtLoginCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 97, 145, -1));
        jPanel1.add(txtLoginContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 137, 145, -1));

        btnLogin.setText("Login");
        btnLogin.setOpaque(false);
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        btnRegistro.setText("Registro");
        btnRegistro.setOpaque(false);
        jPanel1.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        jLabel1.setFont(new java.awt.Font("GWTwoFont Version 1.1", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(209, 194, 170));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GW2CB");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 260, 60));

        fondoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/fondo2.jpg"))); // NOI18N
        jPanel1.add(fondoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDialog Registro;
    public javax.swing.JButton btnAceptar;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnLogin;
    public javax.swing.JButton btnRegistro;
    public javax.swing.JCheckBox chkAleman;
    public javax.swing.JCheckBox chkEspanol;
    public javax.swing.JCheckBox chkFrances;
    public javax.swing.JCheckBox chkIngles;
    public javax.swing.JComboBox combServidor;
    public javax.swing.JLabel etiContrasena;
    public javax.swing.JLabel etiCuenta;
    public javax.swing.JLabel etiEmail;
    public javax.swing.JLabel etiIdiomas;
    public javax.swing.JLabel etiLoginContrasena;
    public javax.swing.JLabel etiLoginCuenta;
    public javax.swing.JLabel etiNivelFrac;
    public javax.swing.JLabel etiRepeContrasena;
    public javax.swing.JLabel etiServidor;
    private javax.swing.JLabel fondoLogin;
    private javax.swing.JLabel fondoRegistro;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel panelIdiomas;
    public javax.swing.JPasswordField txtContrasena;
    public javax.swing.JTextField txtCuenta;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JPasswordField txtLoginContrasena;
    public javax.swing.JTextField txtLoginCuenta;
    public javax.swing.JTextField txtNivelFrac;
    public javax.swing.JPasswordField txtRepeContrasena;
    // End of variables declaration//GEN-END:variables
}
